### DISCUSSION TITLE
Contribution Onboarding

### DISCUSSION THREAD

**Discussion by bdougie** [open-sauced/open-sauced#389] [General] [answered]
## story

As a contributor, I should have a path to contributions. i.e. link to guide, view content of readme, list good first issues.

## proposal

At the moment contributing to open source is a mixed bag. I am proposing that the Repository page provides context on how to get a contribution if no past contributions are present for this repo.

**Comment by bdougie** [comment, marked as answer]
Hear me out:

saucey.yml - name is WIP.

```
onboard:
  chat: /partycorgi
  training: ://link.com 
  path: "..."
  discussionLink: "..."
```
