### ISSUE TITLE
Feature: have .take workflow include comment

### ISSUE THREAD

**Issue by mtfoley** [open-sauced/open-sauced#1077]
### Is your feature request related to a problem? Please describe.

Possible improvements to self-assign workflow

### Describe the solution you'd like

https://clips.twitch.tv/CourageousTallWeaselSeemsGood-g36zdLMfFZJRTvXM

### Describe alternatives you've considered
N/A

**Comment by 0-vortex** [comment]
sounds good !

**Comment by 0-vortex** [comment]
Also clean up the regular expression for it so it doesn't assign by accident like #1065 🔥

**Comment by mtfoley** [comment]
I've found it convenient once or twice to blend that keyword into a bigger comment.  If we need to update the action itself to change the regex, we'd need to do a PR to [take-action repo](https://github.com/bdougie/take-action/blob/main/action.yml#L19).

As for the comment, I'd been thinking of using some of what's [here](https://github.com/actions/github-script#comment-on-an-issue). can anyone think of a reason that wouldn't work? (see below for what `.github/workflows/assign-yourself.yml` would look like.

```yaml
name: Assign
on:
  issue_comment:
    types: [created, edited]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      # .take in an issue comment. 
      - name: take an issue
        uses: bdougie/take-action@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: acknowledge
         uses: actions/github-script@v4
         env:
          GITHUB_TOKEN: ${{ github.token }}
         with:
          script: |
           github.issues.createComment({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             body: '👋 Thanks for taking the issue! Hit us up on our [Discord](https://discord.gg/U2peSNf23P)if you have any questions as you're working through it!'
           })
```
